config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: redirect('/pannels')

  resources :pannels, only: [:create, :edit, :update, :index]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/pannel.rb
class Pannel < ApplicationRecord
    validates :PID, :SID, :date, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pannels_controller.rb
class PannelsController < ApplicationController
    def index
        @pannel = Pannel.new
        @pannels = Pannel.all.order("date ASC")
    end

    def create
        @pannel = Pannel.new(pannel_params)
        @pannels = Pannel.all.order("date ASC")

        if @pannel.amount && @pannel.reading
            @pannel.acceptance = (@pannel.amount/@pannel.reading).round(1)
        elsif @pannel.advisement && @pannel.reading
            @pannel.acceptance = (@pannel.advisement/@pannel.reading).round(1)
        end

        
        if @pannel.amount && @pannel.advisement
            @pannel.accepted = ((@pannel.amount / @pannel.advisement) * 100).round
        else 
            pannels = Pannel.all.order("date ASC")
            index = Pannel.all.length - 1
            last_pannel = pannels[index]

            if last_pannel.nil?
                @pannel.accepted = nil
            else 
                advisement = last_pannel.advisement
            end


            while advisement.nil? && last_pannel
                index -= 1;
                last_pannel = Pannel.all[index]
                if last_pannel.advisement 
                    advisement = last_pannel.advisement
                else 
                    break
                end
            end

            if @pannel.amount && advisement 
                @pannel.accepted = ((@pannel.amount / advisement) * 100).round
            end
        end


        if @pannel.save
            redirect_to pannels_url
        else
            flash.now[:errors] = @pannel.errors.full_messages
            render :index
        end
    end

  def edit
    @pannel = Pannel.find(params[:id])
    render :edit
  end

  def update
    @pannel = Pannel.find(params[:id])

    if @pannel.update(pannel_params)
      redirect_to pannels_url
    else
      flash.now[:errors] = @pannel.errors.full_messages
      render :edit
    end
  end

  private
  def pannel_params
    params.require(:pannel).permit(:PID, :SID, :date, :reading, :amount, :advisement)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Dosis</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= favicon_link_tag asset_path('logo.png') %>
  </head>

  <body id="body">
    <%= yield %>
  </body>
</html>

app/views/pannels/edit.erb
<div id="edit">
    <article id="tables">
        <table style="width:100%">
            <tr>
                <th>PID</th>
                <th>SID</th>
                <th>Date</th>
                <th>Reading</th> 
                <th>Amount</th>
                <th>Advisement</th>
                <th>Acceptance</th>
                <th>% Accepted</th>
            </tr>
                <td><%= @pannel.PID %></td>
                <td><%= @pannel.SID %></td>
                <td><%= @pannel.date.month %>-<%= @pannel.date.day %>-<%= @pannel.date.year %></td>
                <% if @pannel.reading %>
                    <td><%= @pannel.reading %> pts</td>
                <% else %>
                    <td>n/a</td>
                <% end %>
                <% if @pannel.amount %>
                    <td><%= @pannel.amount %> units</td>
                <% else %>
                    <td>n/a</td>
                <% end %>
                <% if @pannel.advisement %>
                    <td><%= @pannel.advisement %> units</td>
                <% else %>
                    <td>n/a</td>
                <% end %>
                <% if @pannel.acceptance %>
                    <td><%= @pannel.acceptance %></td>
                <% else %>
                    <td>n/a</td>
                <% end %>
                <% if @pannel.accepted %>
                    <td><%= @pannel.accepted %>%</td>
                <% else %>
                    <td>n/a</td>
                <% end %>
            </tr>
        </table>
    </article>

    <form class="update" action="<%= pannel_url %>" method="post">
        <input type="hidden" name="_method" value="patch">
        <input type="text" name="pannel[advisement]" placeholder="Advicement" value="<%= @pannel.advisement %>">
        <input class="button" type="submit" name="" value="Update Advisement">
    </form>

</div>

app/views/pannels/index.erb
<div id="index">
    <script src="https://code.highcharts.com/highcharts.js"></script>
    <script src="https://code.highcharts.com/modules/exporting.js"></script>
    <script src="https://code.highcharts.com/modules/export-data.js"></script>
    <div id="container" style="min-width: 310px; height: 400px; margin: 0 auto"></div>

    <% dates = [] %>
    <% readings = [] %>
    <% amounts = [] %>
    <%
        @pannels.each do |pannel|
            dates.push(String(pannel.date.month) + "-" + String(pannel.date.day) + "-" + String(pannel.date.year))
            readings.push(pannel.reading)
            amounts.push(pannel.amount)
        end
    %>

    <script>
    String.prototype.replaceAll = function(search, replacement) {
        var target = this;
        return target.split(search).join(replacement);
    };

        let dates = '<%= dates %>'
        let readings = '<%= readings %>'
        let amounts = '<%= amounts %>'
    </script>

    <%= javascript_include_tag('chart.js') %>
        
    <h1 id="pannels-title">Pannels</h1>
    <article id="tables">
        <table style="width:100%">
        <tr>
            <th>Date</th>
            <th>Reading</th> 
            <th>Amount</th>
            <th>Advisement</th>
            <th>Edit</th>
        </tr>
        <% if @pannels %>
            <% @pannels.each do |pannel| %>
                <tr>
                    <td><%= pannel.date.month %>-<%= pannel.date.day %>-<%= pannel.date.year %></td>
                    <% if pannel.reading %>
                        <td><%= pannel.reading %> pts</td>
                    <% else %>
                        <td>n/a</td>
                    <% end %>
                    <% if pannel.amount %>
                        <td><%= pannel.amount %> units</td>
                    <% else %>
                        <td>n/a</td>
                    <% end %>
                    <% if pannel.advisement %>
                        <td><%= pannel.advisement %> units</td>
                    <% else %>
                        <td>n/a</td>
                    <% end %>
                    <td><a href="<%= edit_pannel_url(pannel) %>">Update Advisement</a></td>
                </tr>
            <% end %>
        <% end %>
        </table>
    </article>
    <article id="tables" style="display: none">
        <table style="width:100%">
        <tr>
            <th>PID</th>
            <th>SID</th>
            <th>Date</th>
            <th>Reading</th> 
            <th>Amount</th>
            <th>Advisement</th>
            <th>Acceptance</th>
            <th>% Accepted</th>
        </tr>
        <% if @pannels %>
            <% @pannels.each do |pannel| %>
                <tr>
                    <td><%= pannel.PID %></td>
                    <td><%= pannel.SID %></td>
                    <td><%= pannel.date.month %>-<%= pannel.date.day %>-<%= pannel.date.year %></td>
                    <% if pannel.reading %>
                        <td><%= pannel.reading %> pts</td>
                    <% else %>
                        <td>n/a</td>
                    <% end %>
                    <% if pannel.amount %>
                        <td><%= pannel.amount %> units</td>
                    <% else %>
                        <td>n/a</td>
                    <% end %>
                    <% if pannel.advisement %>
                        <td><%= pannel.advisement %> units</td>
                    <% else %>
                        <td>n/a</td>
                    <% end %>
                    <% if pannel.acceptance %>
                        <td><%= pannel.acceptance %></td>
                    <% else %>
                        <td>n/a</td>
                    <% end %>
                    <% if pannel.accepted %>
                        <td><%= pannel.accepted %>%</td>
                    <% else %>
                        <td>n/a</td>
                    <% end %>
                </tr>
            <% end %>
        <% end %>
        </table>
    </article>
    <button id="toggle" class="button">Detailed View</button>
    <script>
    $( "button" ).click(function() {
        $( "article" ).toggle();
    });
    </script>


    <h1>Add a New Pannel</h1>

    <form class="create" action="<%= pannels_url %>" method="post">
        <label>
            <input type="text" name="pannel[PID]" placeholder="PID" value="<%= @pannel.PID %>">
        </label>

        <label>
            <input type="text" name="pannel[SID]" placeholder="SID" value="<%= @pannel.SID %>">
        </label>


        <label>
            <input type="date" style="color: rgba(30, 107, 0, 0.55);" name="pannel[date]" placeholder="Date" value="<%= @pannel.date %>">
        </label>

        <label>
            <input type="text" name="pannel[reading]" placeholder="Reading" value="<%= @pannel.reading %>">
        </label>

        <label>
            <input type="text" name="pannel[amount]" placeholder="Amount" value="<%= @pannel.amount %>">
        </label>

        <label>
            <input type="text" name="pannel[advisement]" placeholder="Advicement" value="<%= @pannel.advisement %>">
        </label>

        <input class="button" type="submit" name="" value="Enter New Pannel">
    </form>
    <ul id="errors">
        <% if flash.now[:errors] %>
            <% flash.now[:errors].each do |error| %>
                <li><%= error.upcase %></li>
            <% end %>
        <% end %>
    </ul>
<div>